Vsosh
Zeneriode/Competitive-programming pull request #45
Opened 2023-09-30 11:59 UTC by FedorKatta

2023-09-30 13:15 UTC, Zener085 requested changes
1) Задание было "Решить со второй по четвертую задачи", видимо ты неверно понял, ~~моя вина но признавать этого не хочу~~ тебе еще четвертую надо
2) Вторая задача решена не правильно, пример теста я тебе дал
3) Я немного не понимаю, почему вдруг изменились также другие задачи с прошлого дз (вроде ты должен был 2 файла добавить, а изменилось 8)
4) А можно пж уменьшить код в третьей задаче:)

2023-09-30 13:15 UTC, Zener085 commented on Algoritms/Olympiada 2023-2024/T-Shirts_and_socks.cpp
На тесте `7 6 6 7` выдает `8 7`, но правильно `1 7`

2023-09-30 13:15 UTC, Zener085 commented on Algoritms/Olympiada 2023-2024/prestigious_room.cpp
Безумно много написано кода, мне проверять сложно:( Можно решить намного короче
Но решение вроде правильное, я пытался, но не смог тест какой-нибудь сломать

2023-09-30 13:25 UTC, FedorKatta commented on Algoritms/Olympiada 2023-2024/T-Shirts_and_socks.cpp
Откуда там должно быть 1? Чтобы точно взять красные майку и носки, надо взять 7+1 маек и 6 + 1 носков. Чтобы точно взять синие майку и носки надо взять 6 + 1 маек и 7 + 1 носков!

2023-09-30 14:11 UTC, FedorKatta commented on Algoritms/Olympiada 2023-2024/prestigious_room.cpp
решение < O(n)

2023-09-30 16:23 UTC, Zener085 requested changes
Если задача не решена - зачем её отправлять сюда?
И вопрос с изменением 9 файлов (жду только 3-х) остается открытым

2023-09-30 16:23 UTC, Zener085 commented on Algoritms/Olympiada 2023-2024/sea_battle.cpp
А что мне тут проверять?

2023-09-30 16:24 UTC, Zener085 commented on Algoritms/Olympiada 2023-2024/prestigious_room.cpp
Так писать нельзя
решение O(n) = решение выполняется максимум за n операций. Если ты пишешь решение < O(n), то это можно прочитать как "Решение меньше выполнения максимум n операций", то есть бредятина какая-то

2023-10-13 07:22 UTC, Zener085 approved these changes
Ну я попробую заапрувить, но мне кажется сейчас будет дофига конфликтов

2023-10-13 07:23 UTC, merged